Projectsandaboutsec
mj-e-boc/RonaldMjononoPortfolio pull request #2
Opened 2022-08-18 15:25 UTC by mj-e-boc

-add projects section
-add about section

2022-08-18 16:59 UTC, Qoosim requested changes
Hi @mj-e-boc,

### **Status: Required Changes**  :recycle: 

Good job so far!, :handshake: . You have really put in tons of effort in making it this far and I must commend you for that strength.
However, there are some issues that you still need to work on to go to the next project, but  trust me you are almost there!

## Highlights :green_circle: 

-  No linter errors. :heavy_check_mark: 
-  You used correct Github Flow. :heavy_check_mark: 
-  Professional README. :heavy_check_mark: 
-  Good commit messages. :heavy_check_mark: 

![almost](https://camo.githubusercontent.com/4187074f6b8307d11768c326133ea198a73743e5b747571572effcf028fa3f59/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f52657944344f64526948654c4443526145502f67697068792e676966)


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 16:59 UTC, Qoosim commented on index.html
> +
- [ ] The container of this section should be `<section>` tag. Kindly change the `<div id="projects">` to `<section id="projects">`. 
- [ ] You are missing a `<heading>` tag that is supposed to carry `"My Recent Works`. Kindly fix that part too.
- [ ] I think it would be better to put all the sections in your `<main>` tag which would serve as the grand-parent to every other sections in your project. In your own case, you have this section outside the main section. Kindly move it to the `<main>` tag above this tag `<div id="projects">`

2022-08-18 16:59 UTC, Qoosim commented on index.html
> +      </div>
- [ ] Once you have `<section id="projects">` tag as the parent tag,  this tag `<section class="projectinfo">` can now be ordinary `<div class="projectinfo">` and style it according to the instruction in the project requirements.

2022-08-18 16:59 UTC, Qoosim commented on index.html
> +        </section>
- [ ] Once you have `<section id="projects">` tag as the parent tag,  this tag `<section class="projectinfo">` can now be ordinary `<div class="projectinfo">` and style it according to the instructions in the project requirements.

2022-08-18 16:59 UTC, Qoosim commented on index.html
> +        </section>
- [ ] Once you have `<section id="projects">` tag as the parent tag,  this tag `<section class="projectinfo">` can now be ordinary `<div class="projectinfo">` and style it according to the instruction in the project requirements.

2022-08-18 16:59 UTC, Qoosim commented on index.html
> +        </section>
- [ ] Once you have `<section id="projects">` tag as the parent tag,  this tag `<section class="projectinfo">` can now be ordinary `<div class="projectinfo">` and style it according to the instruction in the project requirements.

2022-08-18 16:59 UTC, Qoosim commented on index.html
> +        </div>
- [ ] Each of the languages should be wrapped in `<ul>` tag and their respective list item should be inside `<li>` tag.

2022-08-18 21:42 UTC, vickymarz requested changes
Hi @mj-e-boc , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 21:42 UTC, vickymarz commented on index.html
> +        <section class="projectinfo">
- [ ] As the previous reviewer has earlier suggested,  replace the `<section class="projectinfo">` with `<div class="projectinfo">` as it is already a part of a section. This will make your code semantic so let's make proper use of the semantic tags 😄 👍🏼

2022-08-18 21:42 UTC, vickymarz commented on index.html
> +        <section class="projectinfo">
- [ ] As the previous reviewer has earlier suggested,  replace the `<section class="projectinfo">` with `<div class="projectinfo">` as it is already a part of a section. This will make your code semantic so let's make proper use of the semantic tags 😄 👍🏼

2022-08-18 21:42 UTC, vickymarz commented on index.html
> +        </ul>
- [ ] Good job implementing the changes by the previous reviewer 👍🏼 . Please kindly note that a `<ul>` tag is used to hold lists or multiple items so you should not specify a separate `<ul>` tag for an individual list(`<li>`)

e.g. 
```
     <ul class="language">
            <li>
                 <img src="./images/Javascript.png" alt="JS icon" />
                  <p>Javascript</p>
             </li>
             <li>
                <img src="./images/Html.png" alt="Html icon" />
                <p>HTML</p>
             </li>
              <li>
                   <img src="./images/Css.png" alt="css icon" />
                   <p>CSS</p>
             </li>
        </ul>
```

2022-08-19 07:28 UTC, zieeco requested changes
Hi @mj-e-boc,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 07:28 UTC, zieeco commented on index.html
> +        <section class="projectinfo">
- This issue is not yet resolved as requested by the previous reviewer, please kindly address the issue :x:

2022-08-19 07:28 UTC, zieeco commented on index.html
> +        <section class="projectinfo">
- This issue is not yet resolved as requested by the previous reviewer, please kindly address the issue :x:

2022-08-19 07:28 UTC, zieeco commented on index.html
> +        </ul>
- This issue is not yet resolved as requested by the previous reviewer, please kindly address the issue :x:

2022-08-19 08:33 UTC, danmainah requested changes
Hi @mj-e-boc , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Github flow was correctly used


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 08:33 UTC, danmainah commented on index.html
> +        </section>
- [ ] @mj-e-boc as previously requested kindly change this section tag to div tag, this is recommended as best practice.

2022-08-19 08:43 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @mj-e-boc , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing all of the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 08:59 UTC, merged