Contactform
mj-e-boc/RonaldMjononoPortfolio pull request #3
Opened 2022-08-23 08:34 UTC by mj-e-boc

-Add index.html file for the contact form 
-Add stylesheet for the contact form

2022-08-23 08:59 UTC, Bondok6 requested changes
Hi @mj-e-boc and @jaamanu  🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights

- No Linter errors ✅
- Use Formspree correctly ✅
- Your repo is professional ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 08:59 UTC, Bondok6 commented on index.html
> +      ></textarea>
- [ ] Great job adding required attributes in email and text inputs 💯, but I suggest adding `required` attribute in the text-area too to activate the validation on submit. 👌

2022-08-23 08:59 UTC, Bondok6 commented on styles.css
> +}
- [ ] According to the requirements you should implement the button interactions (enable, hover, etc.) based on your Figma design. so kindly implement them 👌

![00](https://user-images.githubusercontent.com/45231276/186116700-1917e182-b863-49cc-b134-ab00d1ae5cca.PNG)

![11](https://user-images.githubusercontent.com/45231276/186116767-0b3bf7d0-0c26-4273-91f8-29ea02bd9b72.PNG)

2022-08-24 08:26 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions
-N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-24 08:59 UTC, merged