Page Accessibility
mj-e-boc/RonaldMjononoPortfolio pull request #6
Opened 2022-08-30 12:31 UTC by mj-e-boc

- Page title fixed 
- Image text alternatives inserted 
- Text headings changed, coherent throughout the page
- Color contrast kept the same due to page design 
- Increased main intro font when screen size increase
- Kept interaction according to client design, no labels implemented as yet
- No multimedia information added at the moment
- Fixed page basic structure to ensure that the sematic tags, images, alternative image texts are inline with displayed content

2022-08-30 13:05 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @mj-e-boc and @jaamanu,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-30 13:05 UTC, Omar-Muhamad commented on index.html
> +                <button id="resumebutton" type="button">Get my resume</button>
- [ ] Same here, Please fix the `get my resume` button text color contrast ratio with button background color because It's supposed to be >= 4.5 to enhance site accessibility.

![image](https://user-images.githubusercontent.com/68796232/187443033-048b4a91-f233-46ed-a531-95a18edc16dc.png)

2022-08-30 13:05 UTC, Omar-Muhamad commented on index.html
> +        <button id="submit" type="submit">Get in touch</button>
Same here, Please fix the get my resume button text color contrast ratio with button background color and also between the button background color and the parent element background color because It's supposed to be >= 4.5 to enhance site accessibility.

![image](https://user-images.githubusercontent.com/68796232/187444047-d037f3a7-1427-4188-876a-8d999ff719f5.png)

2022-08-31 10:46 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @mj-e-boc ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-06 12:03 UTC, merged